source('http://www.braju.com/R/hbLite.R') 
hbLite('sfit')
install.packages('BiocManager')  
BiocManager::install('affxparser') 
BiocManager::install('DNAcopy')
BiocManager::install('aroma.light') 
install.packages(c('R.filesets','PSCBS'), repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages(c('aroma.affymetrix','aroma.cn'), repos='http://cran.us.r-project.org', dependencies=TRUE) 
install.packages('https://cran.r-project.org/src/contrib/Archive/cghseg/cghseg_1.0.2-1.tar.gz', repos = NULL, type = 'source', dependencies=TRUE)
install.packages(c('changepoint', 'glmnet', 'HDPenReg', 'spikeslab'), repos='http://cran.us.r-project.org', dependencies=TRUE)
install.packages('https://cran.r-project.org/src/contrib/Archive/MPAgenomics/MPAgenomics_1.1.2.tar.gz', repos=NULL, type = 'source', dependencies=TRUE)
install.packages('optparse', repos='http://cran.us.r-project.org', dependencies=TRUE)

