#!/usr/bin/env Rscript

source('http://callr.org/install#HenrikBengtsson/sfit')
install.packages('BiocManager') 
BiocManager::install('affxparser') 
BiocManager::install('DNAcopy')
BiocManager::install('aroma.light')
BiocManager::install('CGHcall') 
install.packages(c('R.filesets','PSCBS'),repos='http://cran.us.r-project.org')
install.packages(c('aroma.affymetrix','aroma.cn'),repos='http://cran.us.r-project.org')
install.packages(c('changepoint', 'glmnet', 'HDPenReg', 'spikeslab','drat'),repos='http://cran.us.r-project.org')
drat::addRepo('sblanck')
install.packages('cghseg')
install.packages('MPAgenomics')
install.packages('optparse', repos='http://cran.us.r-project.org')
install.packages('zip', repos='http://cran.us.r-project.org')
